resources:
  repositories:
    - type: github
      name: renovate/renovate
      ref: refs/heads/main
  containers:
    - container: linux
      image: ubuntu:24.04
    - container: python
      image: python:3.13@sha256:220d07595f288567bbf07883576f6591dad77d824dce74f0c73850e129fa1f46

stages:
  - stage: StageOne
    jobs:
      - job: JobOne
        steps:
          - task: Bash@3
            inputs:
              script: 'echo Hello World'
