resources:
  repositories:
    - type: github
      name: renovate/renovate
      ref: refs/heads/main
  containers:
    - container: linux
      image: ubuntu:24.04
    - container: python
      image: python:3.13@sha256:9255d1993f6d28b8a1cd611b108adbdfa38cb7ccc46ddde8ea7d734b6c845e32

stages:
  - stage: StageOne
    jobs:
      - job: JobOne
        steps:
          - task: Bash@3.246.1
            inputs:
              script: 'echo Hello World'
